In [ ]:
!git clone https://github.com/OfTheByteQuest/Data-Analytics-Learning-and-Projects.git

%cd Data-Analytics-Learning-and-Projects

Mounted at /content/drive
Cloning into 'Data-Analytics-Learning-and-Projects'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 1), reused 10 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), 629.79 KiB | 8.07 MiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/Data-Analytics-Learning-and-Projects


In [ ]:
import numpy as np

In [ ]:
data = np.genfromtxt('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/example_data.csv',
                     delimiter=';',
                     names=True,
                     dtype=None,
                     encoding='UTF')

In [ ]:
data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [ ]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [ ]:
data[1][1].dtype
data[1][0].dtype

dtype('<U23')

In [ ]:
%%timeit
max([row[3] for row in data])

6.63 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
data.dtype.names

('time', 'place', 'magType', 'mag', 'alert', 'tsunami')

In [ ]:
type(data.dtype.names)

tuple

In [ ]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...)
 |      See PEP 585
 |  
 |  ----------------------------------------------------------------------
 |  

In [ ]:
array_dict = {}

for i, col in enumerate(data.dtype.names):
  array_dict[col] = np.array([row[i] for row in data])

array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [ ]:
%%timeit
array_dict['mag'].max()

1.88 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
np.array([value[array_dict['mag'].argmax()] for value in array_dict.values()])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

In [ ]:
import pandas as pd

In [ ]:
place = pd.Series(array_dict['place'], name='place')
place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

In [ ]:
mag = pd.Series(array_dict['mag'], name="mag")
mag

##mag.index
##mag.values

0    6.7
1    5.2
2    5.7
3    5.7
4    5.6
Name: mag, dtype: float64

In [ ]:
place.index.is_unique
place.index.values

array([0, 1, 2, 3, 4])

_Note: Difference between the addition of numpy array and pandas data-structures_

**Addition in Numpy**

Numpy will use *Vectorization* and *Broadcasting* to perform the operations on array as the result below signifies.

**Addition in Pandas:**

In Pandas, airthmatic operations are only performed on the elements for which the index values match in both the operands being used as displayed by the following output

In [ ]:
np.array([1,2]) + np.array([9])

array([10, 11])

In [ ]:
pd.Series([1,2]) + pd.Series([9])

0    10.0
1     NaN
dtype: float64

In [ ]:
 pd.Series(np.linspace(0, 10, num=5)) + pd.Series(np.linspace(0, 10, num=5), index=pd.Index([1, 2, 3, 4, 5]))


0     NaN
1     2.5
2     7.5
3    12.5
4    17.5
5     NaN
dtype: float64

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [84]:
import datetime as dt

In [81]:
# help(dir)

Help on built-in function dir in module builtins:

dir(...)
    dir([object]) -> list of strings
    
    If called without an argument, return the names in the current scope.
    Else, return an alphabetized list of names comprising (some of) the attributes
    of the given object, and of attributes reachable from it.
    If the object supplies a method named __dir__, it will be used; otherwise
    the default dir() logic is used and returns:
      for a module object: the module's attributes.
      for a class object:  its attributes, and recursively the attributes
        of its bases.
      for any other object: its attributes, its class's attributes, and
        recursively the attributes of its class's base classes.



In [83]:
# pd.date_range??

In [87]:
rng = np.random.default_rng(seed=0)
pd.DataFrame(
    data = {
        'random': rng.random(5),
        'text':['hot', 'warm', 'cool', 'cold', None],
        'truth': [rng.choice([True, False]) for _ in range(5)]
    },
    index = pd.date_range(
        end = dt.date(2019, 4, 21),
        periods = 5,
        freq = '1D',
        name = "date"
    )
)

random  text  truth
date                             
2019-04-17  0.636962   hot  False
2019-04-18  0.269787  warm  False
2019-04-19  0.040974  cool  False
2019-04-20  0.016528  cold  False
2019-04-21  0.813270  None  False

In [86]:
# rng.choice?

In [88]:
pd.DataFrame([
    {'mag' : 5.2, 'place' : 'California'},
    {'mag' : 1.2, 'place' : 'Alaska'},
    {'mag' : 0.2, 'place' : 'California'},
    ])

mag       place
0  5.2  California
1  1.2      Alaska
2  0.2  California

In [89]:
list_of_tuples = [(n, n**2, n**3) for n in range(5)]
pd.DataFrame(
    data = list_of_tuples,
    columns = ['n', 'n_squared', 'n_cubes']
)

n  n_squared  n_cubes
0  0          0        0
1  1          1        1
2  2          4        8
3  3          9       27
4  4         16       64

In [90]:
!wc -l /content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquakes.csv

9333 /content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquakes.csv


In [91]:
!ls /content/Data-Analytics-Learning-and-Projects

Chapter-2  Data-Analytics-Learning-and-Projects


### Shell Commands and Magic Commands

IPython allows to run shell commands directly from IPython terminal. Any command that starts with `!` will be considered a shell command. This is different from using IPython's *Magic Commands* which are written by preceedingt them with `%` symbol. Although, `cd` is a shell command but it is run as a *Magic function* and is written as `%cd` like `%timeit`. Magic commands in Google Colab are written with double percent sign i.e., `%%` so, instead of `%cd` we write `%%cd`. Some commands in IPYthon can be run without the `%%` sign as they are **auto magic** functions and can be toggled with `%automagic` command.

The result of shell commands can be used in the python namespace by storing them in variables. Althought, the result can be read as a list but is different from the typical Python `list` data type and have special IPython data type which can be seem using the `type()` function of Python.

Links for reference:

1. [IPython and Shell Commands](https://jakevdp.github.io/PythonDataScienceHandbook/01.05-ipython-and-shell-commands.html)
2. [Shell Commands in IPython](https://www.python4data.science/en/latest/workspace/ipython/shell.html)
3. [IPYthon reference: Command Line Usage](https://ipython.readthedocs.io/en/stable/interactive/reference.html#system-shell-access)


### Examining files through IPython

Before loading any file in Pyton it's better to analyze it through the commands provided by IPythin kernel. The `ls` commands gives the list of files in any folder. When used with `-lh` flag the info about files is lited in human readable format. We get the info about the size of the file. `wc` commands allows us to get the word count of the file and if follows by `-l` flag, the commands gives us the number of lines in that file.

`!head` allows to peak into the top few lines of the file whereas, `!tail` command allows us to peak at the last few lines of the file. This allows us to know whether the file contains the field name or not. When followed by `-n` flag we can mention the number of lines we want in the output too.

Although, we can use the `!head` command to count the number of fields/ columns in the file, for example

```
head = !head -n 1 /content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquake.csv
print(len(head[0].split(',')))

```
but, we can use a different approach. The `awk` is command in IPython is used for *pattern scanning and processing* we can use like

```
!awk -F',' {print NF; exit} '/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquake.csv'

```

where `-F` allows us to mention the delimiter. Further we can mention the operations we want to do on the file. `{print NF, exit}` prints the value of `NF` variable, which stores the size of the *current record*, and exit the file.

In [98]:
# # Can also be done ls -lh
# /content/Data-Analytics-Learning-and-Projects/Chapter-2/data | grep
# earthquake.csv

content  = !ls -lh /content/Data-Analytics-Learning-and-Projects/Chapter-2/data
content[1]

'-rw-r--r-- 1 root root 3.4M Mar 10 12:40 earthquakes.csv'

In [110]:
!head -n 1 /content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquakes.csv

alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,mmi,net,nst,place,rms,sig,sources,status,time,title,tsunami,type,types,tz,updated,url


In [111]:
df = pd.read_csv('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/earthquakes.csv')

In [113]:
import sqlite3

In [118]:
with sqlite3.connect('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/tsunami.db') as connection:
  pd.read_csv('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/tsunamis.csv').to_sql('tsunamis', connection, index=False, if_exists='replace')

In [121]:
# We, by mistake, had written to 'tsunami' table instead of 'tsunamis' table so, the database would have
# same data in both the tables

with sqlite3.connect('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/tsunami.db') as connection:
  tsunamis = pd.read_sql('SELECT * FROM tsunami', connection)

tsunamis.head()

alert        type                                              title  \
0   None  earthquake  M 5.0 - 165km NNW of Flying Fish Cove, Christm...   
1  green  earthquake            M 6.7 - 262km NW of Ozernovskiy, Russia   
2  green  earthquake        M 5.6 - 128km SE of Kimbe, Papua New Guinea   
3  green  earthquake         M 6.5 - 148km S of Severo-Kuril'sk, Russia   
4  green  earthquake        M 6.2 - 94km SW of Kokopo, Papua New Guinea   

                                             place magType  mag           time  
0  165km NNW of Flying Fish Cove, Christmas Island     mww  5.0  1539459504090  
1                  262km NW of Ozernovskiy, Russia     mww  6.7  1539429023560  
2              128km SE of Kimbe, Papua New Guinea     mww  5.6  1539312723620  
3               148km S of Severo-Kuril'sk, Russia     mww  6.5  1539213362130  
4              94km SW of Kokopo, Papua New Guinea     mww  6.2  1539208835130