In [1]:
from google.colab import drive
drive.mount('/content/drive')

!git clone https://github.com/OfTheByteQuest/Data-Analytics-Learning-and-Projects.git

%cd Data-Analytics-Learning-and-Projects

Mounted at /content/drive
Cloning into 'Data-Analytics-Learning-and-Projects'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 1), reused 10 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (10/10), 629.79 KiB | 8.07 MiB/s, done.
Resolving deltas: 100% (1/1), done.
/content/Data-Analytics-Learning-and-Projects


In [2]:
import numpy as np

In [4]:
data = np.genfromtxt('/content/Data-Analytics-Learning-and-Projects/Chapter-2/data/example_data.csv',
                     delimiter=';',
                     names=True,
                     dtype=None,
                     encoding='UTF')

In [5]:
data

array([('2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia', 'mww', 6.7, 'green', 1),
       ('2018-10-13 04:34:15.580', '25km E of Bitung, Indonesia', 'mww', 5.2, 'green', 0),
       ('2018-10-13 00:13:46.220', '42km WNW of Sola, Vanuatu', 'mww', 5.7, 'green', 0),
       ('2018-10-12 21:09:49.240', '13km E of Nueva Concepcion, Guatemala', 'mww', 5.7, 'green', 0),
       ('2018-10-12 02:52:03.620', '128km SE of Kimbe, Papua New Guinea', 'mww', 5.6, 'green', 1)],
      dtype=[('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [6]:
data.dtype

dtype([('time', '<U23'), ('place', '<U37'), ('magType', '<U3'), ('mag', '<f8'), ('alert', '<U5'), ('tsunami', '<i8')])

In [7]:
data[1][1].dtype
data[1][0].dtype

dtype('<U23')

In [8]:
%%timeit
max([row[3] for row in data])

6.63 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
data.dtype.names

('time', 'place', 'magType', 'mag', 'alert', 'tsunami')

In [10]:
type(data.dtype.names)

tuple

In [11]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |  
 |  __class_getitem__(...)
 |      See PEP 585
 |  
 |  ----------------------------------------------------------------------
 |  

In [12]:
array_dict = {}

for i, col in enumerate(data.dtype.names):
  array_dict[col] = np.array([row[i] for row in data])

array_dict

{'time': array(['2018-10-13 11:10:23.560', '2018-10-13 04:34:15.580',
        '2018-10-13 00:13:46.220', '2018-10-12 21:09:49.240',
        '2018-10-12 02:52:03.620'], dtype='<U23'),
 'place': array(['262km NW of Ozernovskiy, Russia', '25km E of Bitung, Indonesia',
        '42km WNW of Sola, Vanuatu',
        '13km E of Nueva Concepcion, Guatemala',
        '128km SE of Kimbe, Papua New Guinea'], dtype='<U37'),
 'magType': array(['mww', 'mww', 'mww', 'mww', 'mww'], dtype='<U3'),
 'mag': array([6.7, 5.2, 5.7, 5.7, 5.6]),
 'alert': array(['green', 'green', 'green', 'green', 'green'], dtype='<U5'),
 'tsunami': array([1, 0, 0, 0, 1])}

In [13]:
%%timeit
array_dict['mag'].max()

1.88 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
np.array([value[array_dict['mag'].argmax()] for value in array_dict.values()])

array(['2018-10-13 11:10:23.560', '262km NW of Ozernovskiy, Russia',
       'mww', '6.7', 'green', '1'], dtype='<U32')

In [15]:
import pandas as pd

In [16]:
place = pd.Series(array_dict['place'], name='place')
place

0          262km NW of Ozernovskiy, Russia
1              25km E of Bitung, Indonesia
2                42km WNW of Sola, Vanuatu
3    13km E of Nueva Concepcion, Guatemala
4      128km SE of Kimbe, Papua New Guinea
Name: place, dtype: object

In [17]:
mag = pd.Series(array_dict['mag'], name="mag")
mag

##mag.index
##mag.values

0    6.7
1    5.2
2    5.7
3    5.7
4    5.6
Name: mag, dtype: float64

In [26]:
place.index.is_unique
place.index.values

array([0, 1, 2, 3, 4])

_Note: Difference between the addition of numpy array and pandas data-structures_

**Addition in Numpy**

Numpy will use *Vectorization* and *Broadcasting* to perform the operations on array as the result below signifies.

**Addition in Pandas:**

In Pandas, airthmatic operations are only performed on the elements for which the index values match in both the operands being used as displayed by the following output

In [27]:
np.array([1,2]) + np.array([9])

array([10, 11])

In [28]:
pd.Series([1,2]) + pd.Series([9])

0    10.0
1     NaN
dtype: float64

In [30]:
 pd.Series(np.linspace(0, 10, num=5)) + pd.Series(np.linspace(0, 10, num=5), index=pd.Index([1, 2, 3, 4, 5]))


0     NaN
1     2.5
2     7.5
3    12.5
4    17.5
5     NaN
dtype: float64

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])